version: '3'

services: 
  devconnector-api:
    container_name: devconnector-api
    build: ./devconnector-api
    command: npm run dev
    env_file: ./devconnector-api/.env
    ports: 
      - 5000:5000
    volumes: 
      - ./devconnector-api:/usr/src/app
      - api_modules:/usr/src/app/node_modules

  devconnector-app:
    container_name: devconnector-app
    build: ./devconnector-app
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./devconnector-app:/usr/src/app
      - app_modules:/usr/src/app/node_modules
    external_links:
      - devconnector-api




volumes:
  api_modules:
  app_modules: 